name: 'Deploy DCE'

on:
  push:
    branches: [ "main" , "qa" ]
  pull_request:
    branches: [ "main" , "qa" ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'deploy arch'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./modules

    steps:
    - name: Configure aws prod credentials
      if: github.ref == 'refs/heads/prod'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::932356933194:role/github_action
        aws-region: eu-west-1

    - name: Configure aws qa credentials
      if: github.ref == 'refs/heads/qa'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::630116293498:role/github_action
        aws-region: eu-west-1

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 0.12.31
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false

      # On push to "main", deploy the Terraform infrastructure
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

    - name: Deploy Code
      working-directory: ./
      run: make deploy